version: "3.9"

services:
  backtesting-workshop:
    container_name: backtesting-workshop
    image: utkusarioglu/conda-econ-devcontainer:experiment-feat-music-sequencer-8

    environment:
      PYTHONPATH: /utkusarioglu-com/workshops/backtesting-workshop
      ARTIFACTS_ABSPATH: /utkusarioglu-com/workshops/backtesting-workshop/artifacts
      ASSETS_ABSPATH: /utkusarioglu-com/workshops/backtesting-workshop/assets
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/workshops/backtesting-workshop
