services:
  backtesting-workshop:
    container_name: backtesting-workshop
    image: utkusarioglu/conda-econ-devcontainer:3.13-ubuntu-test-25

    environment:
      PYTHONPATH: /utkusarioglu-com/workshops/backtesting-workshop
      ARTIFACTS_ABSPATH: /utkusarioglu-com/workshops/backtesting-workshop/artifacts
      ASSETS_ABSPATH: /utkusarioglu-com/workshops/backtesting-workshop/assets
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/workshops/backtesting-workshop

  backtesting-workshop-postgres:
    container_name: backtesting-workshop-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - type: bind
        source: ../src/sql
        target: /sql
      - type: bind
        source: ../src/sql/migrations/init
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

volumes:
  postgres-data:
    name: backtesting-workshop-postgres-data
